### ISSUE TITLE
Reset-SecretStore doesn't prompt for a new password

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/SecretStore#34]
I was confused by the behaviour of `Reset-SecretStore`. It just succeeded without prompting me for a new password.

Only when I used `Get-Secret` was a I prompted to create a new password.

I would have expected to need to provide a new password on reset.

**Comment by rjmholt** [comment]
When I used `Get-Secret` I expected it to prompt me for my old password. I did get a prompt, but assumed it was for my old password (which I'm supposed to have forgotten).

I didn't understand it was for a new secret and just entered through it, and now have a password I'm not sure about.

**Comment by PaulHigin** [comment]
Implemented for preview3.

**Comment by smoofy** [comment]
I did not agree with @rjmholt, according [approved verb from PowerShell documentation](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.1), Reset should only set a resource back to its original state. In this case, state just after Register-SecretVault.

Due to this "Creating a new Microsoft.PowerShell.SecretStore vault" prompt, using `Reset-SecretStore` non interactively lead to an error.

An output could display the procedure to initialize vault again.
