### ISSUE TITLE
Exception when calling `Get-SecretStoreConfiguration` and `Set-Secret`

### ISSUE THREAD

**Issue by AjayKMehta** [PowerShell/SecretStore#56]
I installed both `SecretStore` and `SecretManagement` modules and tried to follow the examples in the [blog post announcing the release](https://devblogs.microsoft.com/powershell/secretmanagement-and-secretstore-are-generally-available/). However, I get the exceptions shown below:

![Screenshot 2021-03-26 103957](https://user-images.githubusercontent.com/11180071/112671616-a5b27b00-8e1f-11eb-839b-c42e2e792590.png)

PS Version info:

```shell
Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PaulHigin** [comment]
I have not seen this error.  I suspect there may be some conflict between previous versions.  Make sure you uninstall any previous versions of SecretStore and SecretManagement.  Also try unregistering any extension vaults and re-register.  Be sure and try with a new instance of PowerShell shell.

If you continue seeing this, examine the error record exception and innerexception that includes stack information.
```powershell
$err = Get-Error
$err.Exception
$err.Exception.StackTrace
$err.Exception.InnerException
$err.Exception.InnerException.StackStrace
```

Otherwise, I would need a repro.

**Comment by PaulHigin** [comment]
Or just run `Get-Error` and it will dump all error information.
Another thing you can try is to reset the SecretStore.  If you used an older version there may be a conflict (although I haven't seen any).
But beware as it erases all of your existing secrets.
```powershell
Reset-SecretStore
```

**Comment by AjayKMehta** [comment]
Thanks, @PaulHigin. I initially had installed a preview version which I deleted.

`Reset-SecretStore` resolved the issue.

**Comment by JSPATRICK1** [comment]
#95
